"""
V21 TITAN FAST — 2-PHASE OPTIMIZATION SWEEP
==============================================
Phase 1: Fast sweep (12 configs × 20K max) → identify top 4 configs
Phase 2: Deep run (top 4 × 50K) → final champion

Optimizations vs v21_titan.py:
- Shared pool cache (build once per draw)
- Pre-built weight arrays (reuse across same pool)
- 2-phase reduces total combos generated by ~60%

V20 baseline: APEX-RAW = 9 hits @50K, 4 hits @18K, 3 hits @10K
"""
import sys, os, math, json, time, random
import numpy as np
from collections import Counter, defaultdict
from itertools import combinations

sys.stdout.reconfigure(encoding='utf-8')
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from scraper.data_manager import get_mega645_numbers

MAX = 45; PICK = 6


# ============================================================
# 9-SIGNAL ENGINE (same as v21_titan.py)
# ============================================================

def compute_signals(data, at_index):
    """9-signal engine: V20's 8 + pair-boost."""
    relevant = data[:at_index]; n = len(relevant)
    if n < 50: return {num: PICK/MAX for num in range(1, MAX+1)}
    last = set(relevant[-1][:PICK]); base_p = PICK/MAX
    scores = {num: 0.0 for num in range(1, MAX+1)}

    # Signal 1: Multi-window frequency
    for w, wt in [(3,4),(5,3),(10,2),(20,1.5),(50,1)]:
        if n < w: continue
        fc = Counter()
        for d in relevant[-w:]:
            for num in d[:PICK]: fc[num] += 1
        for num in range(1, MAX+1): scores[num] += fc.get(num,0)/w * wt

    # Signal 2: Follow-on transition
    follow = defaultdict(Counter); pc = Counter()
    for i in range(n-1):
        for p in relevant[i][:PICK]:
            pc[p] += 1
            for nx in relevant[i+1][:PICK]: follow[p][nx] += 1
    for num in range(1, MAX+1):
        tf = sum(follow[p].get(num,0) for p in last)
        tp = sum(pc[p] for p in last)
        if tp > 0: scores[num] += (tf/tp/base_p-1)*3

    # Signal 3: KNN similarity
    knn = Counter()
    for i in range(n-2):
        sim = len(set(relevant[i][:PICK]) & last)
        if sim >= 2:
            for num in relevant[i+1][:PICK]: knn[num] += sim*sim
    mx = max(knn.values()) if knn else 1
    for num in range(1, MAX+1): scores[num] += knn.get(num,0)/mx*2.5

    # Signal 4: Gap/due analysis
    ls_idx = {}; gs, gn = defaultdict(float), defaultdict(int)
    for i, d in enumerate(relevant):
        for num in d[:PICK]:
            if num in ls_idx: gs[num] += i-ls_idx[num]; gn[num] += 1
            ls_idx[num] = i
    for num in range(1, MAX+1):
        if gn[num] < 5: continue
        mg = gs[num]/gn[num]; cg = n-ls_idx.get(num,0)
        if cg > mg*1.3: scores[num] += min((cg/mg-1)*1.5, 3)

    # Signal 5: Pair frequency
    pf = Counter()
    for d in relevant[-200:]:
        for p in combinations(sorted(d[:PICK]), 2): pf[p] += 1
    for num in range(1, MAX+1):
        scores[num] += sum(pf.get(tuple(sorted([p,num])),0) for p in last)*0.05

    # Signal 6: Inertia/autocorrelation
    ww = min(100, n)
    iai, ic = Counter(), Counter()
    for i in range(max(0,n-ww), n-1):
        curr, nxt = set(relevant[i][:PICK]), set(relevant[i+1][:PICK])
        for num in curr:
            ic[num] += 1
            if num in nxt: iai[num] += 1
    for num in range(1, MAX+1):
        if num in last and ic[num] > 5:
            scores[num] += (iai[num]/ic[num]-base_p)*3

    # Signal 7: Markov-2
    if n >= 3:
        last2 = set(relevant[-2][:PICK])
        follow2 = defaultdict(Counter); pc2 = Counter()
        for i in range(n-2):
            for p in relevant[i][:PICK]:
                pc2[p] += 1
                for nx in relevant[i+2][:PICK]: follow2[p][nx] += 1
        for num in range(1, MAX+1):
            tf2 = sum(follow2[p].get(num,0) for p in last2)
            tp2 = sum(pc2[p] for p in last2)
            if tp2 > 0: scores[num] += (tf2/tp2/base_p-1)*2

    # Signal 8: Digit-pattern
    if n >= 10:
        digit_freq = Counter()
        for d in relevant[-10:]:
            for num in d[:PICK]: digit_freq[num % 10] += 1
        total_digits = sum(digit_freq.values())
        for num in range(1, MAX+1):
            d = num % 10
            expected_digit = total_digits / 10
            actual_digit = digit_freq.get(d, 0)
            if actual_digit > expected_digit * 1.3:
                scores[num] += min((actual_digit/expected_digit - 1) * 1.0, 2)

    # Signal 9: Pair-boost
    top12 = sorted(scores.items(), key=lambda x: -x[1])[:12]
    top12_nums = [num for num, _ in top12]
    for num in range(1, MAX+1):
        if num in top12_nums: continue
        pair_bonus = sum(pf.get(tuple(sorted([num, t])), 0) for t in top12_nums)
        scores[num] += pair_bonus * 0.03

    return scores


# ============================================================
# POOL BUILDERS
# ============================================================

def build_diverse_pool(data, at_index, scores, max_pool):
    relevant = data[:at_index]; n = at_index
    last_set = set(relevant[-1][:PICK])
    ranked = sorted(scores.items(), key=lambda x: -x[1])
    pools = set()
    pools.update(num for num, _ in ranked[:15])
    for w in [30, 50, 100]:
        fc = Counter(num for d in relevant[-min(w,n):] for num in d[:PICK])
        pools.update(num for num, _ in fc.most_common(15))
    ls = {}
    for i, d in enumerate(relevant):
        for num in d[:PICK]: ls[num] = i
    pools.update(sorted(range(1,MAX+1), key=lambda x: -(n-ls.get(x,0)))[:15])
    fc = Counter()
    for i in range(n-1):
        for p in relevant[i][:PICK]:
            if p in last_set:
                for nx in relevant[i+1][:PICK]: fc[nx] += 1
    pools.update(num for num, _ in fc.most_common(15))
    kc = Counter()
    for i in range(n-2):
        sim = len(set(relevant[i][:PICK]) & last_set)
        if sim >= 3:
            for num in relevant[i+1][:PICK]: kc[num] += sim*sim
    pools.update(num for num, _ in kc.most_common(15))
    cc = Counter()
    for d in relevant[-200:]:
        ds = set(d[:PICK]); ov = ds & last_set
        if len(ov) >= 2:
            for num in ds-last_set: cc[num] += len(ov)
    pools.update(num for num, _ in cc.most_common(15))
    for num in last_set:
        for delta in [-2,-1,1,2]:
            nb = num+delta
            if 1<=nb<=MAX: pools.add(nb)
    return sorted(pools, key=lambda x: -scores.get(x,0))[:max_pool]


def build_fusion_pool(data, at_index, scores, target_size):
    relevant = data[:at_index]; n = at_index
    diverse = set(build_diverse_pool(data, at_index, scores, 40))
    ranked = sorted(scores.items(), key=lambda x: -x[1])
    signal = set(num for num, _ in ranked[:35])

    ls = {}
    for i, d in enumerate(relevant):
        for num in d[:PICK]: ls[num] = i
    gap_due = set(sorted(range(1, MAX+1), key=lambda x: -(n - ls.get(x, 0)))[:15])

    if n >= 3:
        last2 = set(relevant[-2][:PICK])
        m2 = Counter()
        for i in range(n-2):
            for p in relevant[i][:PICK]:
                if p in last2:
                    for nx in relevant[i+2][:PICK]: m2[nx] += 1
        markov2 = set(num for num, _ in m2.most_common(15))
    else:
        markov2 = set()

    # Triplet transition pool
    if n >= 3:
        last_set = set(relevant[-1][:PICK])
        trip = Counter()
        for i in range(n-2):
            s1 = set(relevant[i][:PICK])
            overlap = s1 & last_set
            if len(overlap) >= 2 and i+2 < n:
                for num in relevant[i+2][:PICK]:
                    trip[num] += len(overlap)
        triplet_pool = set(num for num, _ in trip.most_common(10))
    else:
        triplet_pool = set()

    fusion = diverse | signal | gap_due | markov2 | triplet_pool
    return sorted(fusion, key=lambda x: -scores.get(x, 0))[:target_size]


# ============================================================
# OPTIMIZED PORTFOLIO GENERATOR
# ============================================================

def _make_weights(pool, scores, method):
    n = len(pool)
    ranked = sorted(pool, key=lambda x: -scores.get(x,0))
    wp = []
    if method == 'linear':
        for i, num in enumerate(ranked):
            wp.extend([num] * max(1, n-i))
    elif method == 'exp':
        for i, num in enumerate(ranked):
            wp.extend([num] * max(1, min(int(2**((n-i)/4)), 300)))
    elif method == 'step':
        for i, num in enumerate(ranked):
            wp.extend([num] * (10 if i < 12 else 1))
    elif method == 'zone':
        for i, num in enumerate(ranked):
            if i < 10: weight = 8
            elif i < 25: weight = 3
            else: weight = 1
            wp.extend([num] * weight)
    return wp


def gen_hybrid(pool, scores, n_tickets, rng, sort_ratio=0.7):
    """Hybrid SORT+SEQ with configurable ratio."""
    n = len(pool)
    if n < PICK: return []

    raw_target = int(n_tickets * 1.3)  # Reduced from 1.4 for speed
    methods = ['linear', 'exp', 'step', 'zone']
    wps = [_make_weights(pool, scores, m) for m in methods]
    per = raw_target // len(methods)

    selected = set()
    for j, wp in enumerate(wps):
        target = per if j < len(methods)-1 else raw_target - (len(methods)-1)*per
        att = 0
        max_att = target * 10  # Reduced from 15 for speed
        while len(selected) < (j+1)*per and att < max_att:
            att += 1
            picked = set()
            while len(picked) < PICK:
                picked.add(rng.choice(wp))
            selected.add(tuple(sorted(picked)))

    raw_list = list(selected)
    scored = [(c, sum(scores.get(num,0) for num in c)) for c in raw_list]
    scored.sort(key=lambda x: -x[1])

    sort_count = int(n_tickets * sort_ratio)
    diverse_count = n_tickets - sort_count

    sorted_portion = [c for c, _ in scored[:sort_count]]
    remaining = [c for c, _ in scored[sort_count:]]

    if remaining and diverse_count > 0:
        sorted_set = set(sorted_portion)
        diverse_pool = [c for c in remaining if c not in sorted_set]
        if diverse_pool:
            diverse_portion = [diverse_pool[rng.randint(0, len(diverse_pool)-1)]
                             for _ in range(min(diverse_count, len(diverse_pool)))]
        else:
            diverse_portion = []
    else:
        diverse_portion = []

    portfolio = sorted_portion + diverse_portion
    return portfolio[:n_tickets]


def gen_multi_seed(pool, scores, n_tickets, base_seed, ti, sort_ratio=0.7):
    """Multi-seed: 3 seeds → union → score-sort → top n_tickets."""
    all_combos = set()
    seeds = [base_seed + ti * 10000 + s * 777 for s in range(3)]
    per_seed = int(n_tickets * 0.5)  # Each seed 50% → union ~1.3x

    for seed_val in seeds:
        rng = random.Random(seed_val)
        port = gen_hybrid(pool, scores, per_seed, rng, sort_ratio)
        all_combos.update(port)

    scored = [(c, sum(scores.get(num,0) for num in c)) for c in all_combos]
    scored.sort(key=lambda x: -x[1])
    return [c for c, _ in scored[:n_tickets]]


# ============================================================
# MAIN BACKTEST — 2-PHASE
# ============================================================

def run():
    data = get_mega645_numbers()
    N = len(data); t0 = time.time()

    print("=" * 90)
    print("  🔱 V21 TITAN FAST — 2-PHASE OPTIMIZATION")
    print(f"  {N} draws | 9-signal | Phase1: 12 configs @20K | Phase2: Top4 @50K")
    print("=" * 90)

    WARMUP = 200
    n_test = N - WARMUP

    # ═══════════════════════════════════════
    # PHASE 1: FAST SWEEP — 12 configs @ 20K max
    # ═══════════════════════════════════════

    P1_CONFIGS = {}

    # Pool size sweep (sort ratio 0.7)
    for ps in [42, 43, 44, 45]:
        P1_CONFIGS[f'F{ps}'] = {'pool_size': ps, 'sort_ratio': 0.7, 'multi_seed': False}

    # Sort ratio sweep (pool 42)
    for sr in [0.5, 0.6, 0.8, 0.9, 1.0]:
        P1_CONFIGS[f'SR{int(sr*100)}'] = {'pool_size': 42, 'sort_ratio': sr, 'multi_seed': False}

    # Multi-seed variants
    P1_CONFIGS['MS-F42'] = {'pool_size': 42, 'sort_ratio': 0.7, 'multi_seed': True}
    P1_CONFIGS['MS-F44'] = {'pool_size': 44, 'sort_ratio': 0.7, 'multi_seed': True}
    P1_CONFIGS['MS-SR80'] = {'pool_size': 42, 'sort_ratio': 0.8, 'multi_seed': True}

    P1_PORTS = [5000, 10000, 18000, 20000]  # Smaller for speed

    results_p1 = {}
    for cfg_name in P1_CONFIGS:
        results_p1[cfg_name] = {pt: {'six': 0, 'five': 0, 'four': 0, 'det': []} for pt in P1_PORTS}

    contain = {ps: 0 for ps in [42, 43, 44, 45]}

    print(f"\n  ═══ PHASE 1: FAST SWEEP ═══")
    print(f"  {len(P1_CONFIGS)} configs × {len(P1_PORTS)} portfolio sizes (max 20K)")
    print(f"  Walk-forward: {n_test} draws")
    print(f"{'━'*90}")

    for ti in range(n_test):
        te = WARMUP + ti
        actual = set(data[te][:PICK])
        sc = compute_signals(data, te)

        # Build pools (cache for all pool sizes)
        pool_cache = {}
        for ps in [42, 43, 44, 45]:
            pool_cache[ps] = build_fusion_pool(data, te, sc, ps)
            if len(actual & set(pool_cache[ps])) >= 6:
                contain[ps] += 1

        # Run each config
        for cfg_name, cfg in P1_CONFIGS.items():
            ps = cfg['pool_size']
            pool = pool_cache[ps]
            sr = cfg['sort_ratio']
            max_port = max(P1_PORTS)

            if cfg['multi_seed']:
                portfolio = gen_multi_seed(pool, sc, max_port, 42, ti, sr)
            else:
                seed_val = 42 + ti * 10000 + hash(cfg_name) % 9973
                rng = random.Random(seed_val)
                portfolio = gen_hybrid(pool, sc, max_port, rng, sr)

            for pt in P1_PORTS:
                port = portfolio[:min(pt, len(portfolio))]
                if port:
                    best = max(len(actual & set(c)) for c in port)
                else:
                    best = 0
                if best >= 6:
                    results_p1[cfg_name][pt]['six'] += 1
                    results_p1[cfg_name][pt]['det'].append((te, sorted(actual)))
                if best >= 5: results_p1[cfg_name][pt]['five'] += 1
                if best >= 4: results_p1[cfg_name][pt]['four'] += 1

        if (ti+1) % 50 == 0:
            el = time.time() - t0
            eta = el/(ti+1)*(n_test-ti-1)
            ranking = [(k, results_p1[k][20000]['six']) for k in results_p1]
            ranking.sort(key=lambda x: -x[1])
            top3 = " | ".join(f"{k}={s}" for k, s in ranking[:3])
            print(f"  [{ti+1:4d}/{n_test}] @20K: {top3} | "
                  f"PC42={contain[42]} PC44={contain[44]} | {el:.0f}s ETA:{eta/60:.1f}m")
            sys.stdout.flush()

    p1_elapsed = time.time() - t0

    # ═══════════════════════════════════════
    # PHASE 1 RESULTS
    # ═══════════════════════════════════════
    print(f"\n{'═'*90}")
    print(f"  📊 PHASE 1 RESULTS ({p1_elapsed/60:.1f}min)")
    print(f"{'═'*90}")

    print(f"\n  Pool Containment:")
    for ps in [42, 43, 44, 45]:
        pct = contain[ps]/n_test*100
        print(f"    Fusion {ps}: {pct:.2f}% ({contain[ps]}/{n_test})")

    # Score each config by composite metric: weighted sum across portfolio sizes
    composite = {}
    for cfg_name in P1_CONFIGS:
        score = 0
        for pt in P1_PORTS:
            r = results_p1[cfg_name][pt]
            # Weight: bigger at smaller portfolio (efficiency matters more)
            weight = {5000: 4, 10000: 3, 18000: 2, 20000: 1}[pt]
            score += r['six'] * weight + r['five'] * weight * 0.1
        composite[cfg_name] = score

    ranked_configs = sorted(composite.items(), key=lambda x: -x[1])

    for pt in P1_PORTS:
        print(f"\n  @{pt//1000}K:")
        print(f"  {'Config':<18} │ {'6/6':>5} {'5/6':>5} {'4/6':>5}")
        print(f"  {'─'*18} │ {'─'*5} {'─'*5} {'─'*5}")
        rows = [(k, results_p1[k][pt]['six'], results_p1[k][pt]['five'], results_p1[k][pt]['four'])
                for k in P1_CONFIGS]
        rows.sort(key=lambda x: (-x[1], -x[2]))
        for k, s6, s5, s4 in rows:
            bar = '█' * s6
            marker = ' ⭐' if s6 == rows[0][1] and s6 > 0 else ''
            print(f"  {k:<18} │ {s6:>5} {s5:>5} {s4:>5}  {bar}{marker}")

    # Select top 4 for Phase 2
    top4 = [k for k, _ in ranked_configs[:4]]
    print(f"\n  🏆 TOP 4 FOR PHASE 2: {top4}")
    print(f"  Composite scores: {[(k, round(s,1)) for k, s in ranked_configs[:4]]}")

    # ═══════════════════════════════════════
    # PHASE 2: DEEP RUN — Top 4 @ 30K, 50K
    # ═══════════════════════════════════════
    t2 = time.time()
    P2_PORTS = [30000, 50000]

    results_p2 = {}
    for cfg_name in top4:
        results_p2[cfg_name] = {pt: {'six': 0, 'five': 0, 'four': 0, 'det': []} for pt in P2_PORTS}

    print(f"\n  ═══ PHASE 2: DEEP RUN ═══")
    print(f"  {len(top4)} configs × {len(P2_PORTS)} portfolio sizes (30K, 50K)")
    print(f"{'━'*90}")

    for ti in range(n_test):
        te = WARMUP + ti
        actual = set(data[te][:PICK])
        sc = compute_signals(data, te)

        for cfg_name in top4:
            cfg = P1_CONFIGS[cfg_name]
            ps = cfg['pool_size']
            pool = build_fusion_pool(data, te, sc, ps)
            sr = cfg['sort_ratio']
            max_port = max(P2_PORTS)

            if cfg['multi_seed']:
                portfolio = gen_multi_seed(pool, sc, max_port, 42, ti, sr)
            else:
                seed_val = 42 + ti * 10000 + hash(cfg_name) % 9973
                rng = random.Random(seed_val)
                portfolio = gen_hybrid(pool, sc, max_port, rng, sr)

            for pt in P2_PORTS:
                port = portfolio[:min(pt, len(portfolio))]
                if port:
                    best = max(len(actual & set(c)) for c in port)
                else:
                    best = 0
                if best >= 6:
                    results_p2[cfg_name][pt]['six'] += 1
                    results_p2[cfg_name][pt]['det'].append((te, sorted(actual)))
                if best >= 5: results_p2[cfg_name][pt]['five'] += 1
                if best >= 4: results_p2[cfg_name][pt]['four'] += 1

        if (ti+1) % 50 == 0:
            el = time.time() - t2
            eta = el/(ti+1)*(n_test-ti-1)
            ranking = [(k, results_p2[k][50000]['six']) for k in top4]
            ranking.sort(key=lambda x: -x[1])
            top_str = " | ".join(f"{k}={s}" for k, s in ranking[:3])
            print(f"  [{ti+1:4d}/{n_test}] @50K: {top_str} | {el:.0f}s ETA:{eta/60:.1f}m")
            sys.stdout.flush()

    p2_elapsed = time.time() - t2
    total_elapsed = time.time() - t0

    # ═══════════════════════════════════════
    # FINAL RESULTS
    # ═══════════════════════════════════════
    ALL_PORTS = P1_PORTS + P2_PORTS

    # Merge results
    results_all = {}
    for cfg_name in P1_CONFIGS:
        results_all[cfg_name] = {}
        for pt in P1_PORTS:
            results_all[cfg_name][pt] = results_p1[cfg_name][pt]
        for pt in P2_PORTS:
            if cfg_name in results_p2:
                results_all[cfg_name][pt] = results_p2[cfg_name][pt]
            else:
                results_all[cfg_name][pt] = {'six': 0, 'five': 0, 'four': 0, 'det': []}

    print(f"\n{'═'*90}")
    print(f"  🔱 V21 TITAN — FINAL RESULTS ({n_test} tests, {total_elapsed/60:.1f}min)")
    print(f"{'═'*90}")

    print(f"\n  Pool Containment:")
    for ps in [42, 43, 44, 45]:
        pct = contain[ps]/n_test*100
        cpk = math.comb(ps, PICK)
        print(f"    Fusion {ps}: {pct:.2f}% ({contain[ps]}/{n_test}), C({ps},6)={cpk:,}")

    # Full results table for top 4 across all portfolio sizes
    print(f"\n{'─'*90}")
    print(f"  🏆 CHAMPION TABLE (Top 4 configs):")
    print(f"\n  {'Config':<18} │ {'@5K':>5} {'@10K':>5} {'@18K':>5} {'@20K':>5} │ {'@30K':>5} {'@50K':>5}")
    print(f"  {'─'*18} │ {'─'*5} {'─'*5} {'─'*5} {'─'*5} │ {'─'*5} {'─'*5}")

    for cfg_name in top4:
        row = []
        for pt in P1_PORTS:
            row.append(results_all[cfg_name][pt]['six'])
        for pt in P2_PORTS:
            row.append(results_all[cfg_name][pt]['six'])
        total = sum(row)
        print(f"  {cfg_name:<18} │ {row[0]:>5} {row[1]:>5} {row[2]:>5} {row[3]:>5} │ {row[4]:>5} {row[5]:>5}  Σ={total}")

    # ALL configs at P1 sizes
    print(f"\n{'─'*90}")
    print(f"  📊 ALL CONFIGS @20K:")
    print(f"  {'Config':<18} │ {'6/6':>5} {'5/6':>5} │ {'Composite':>10}")
    print(f"  {'─'*18} │ {'─'*5} {'─'*5} │ {'─'*10}")
    for cfg_name, comp_score in ranked_configs:
        s6 = results_p1[cfg_name][20000]['six']
        s5 = results_p1[cfg_name][20000]['five']
        print(f"  {cfg_name:<18} │ {s6:>5} {s5:>5} │ {comp_score:>10.1f}")

    # vs V20 baseline
    print(f"\n{'─'*90}")
    print(f"  📊 VS V20 APEX-RAW BASELINE:")
    v20_baselines = {5000: 1, 10000: 3, 18000: 4, 20000: 4, 30000: 7, 50000: 9}
    for pt in ALL_PORTS:
        best_cfg = None; best_six = -1
        for cfg_name in (top4 if pt in P2_PORTS else P1_CONFIGS.keys()):
            s6 = results_all[cfg_name][pt]['six']
            if s6 > best_six:
                best_six = s6; best_cfg = cfg_name
        baseline = v20_baselines.get(pt, 0)
        delta = best_six - baseline
        arrow = '🔺' if delta > 0 else ('🔻' if delta < 0 else '➖')
        print(f"    @{pt//1000:>2}K: {best_cfg:<18} = {best_six:>3} hits ({arrow} {delta:+d} vs V20={baseline})")

    # 6/6 draw details for best @50K
    best_50k_cfg = max(top4, key=lambda c: results_p2[c][50000]['six'])
    det = results_p2[best_50k_cfg][50000]['det']
    if det:
        print(f"\n  🎉 6/6 DRAWS ({best_50k_cfg} @50K):")
        for idx, nums in det[:15]:
            print(f"    Draw #{idx}: {nums}")

    # Group analysis
    print(f"\n{'─'*90}")
    print(f"  📊 GROUP ANALYSIS @20K:")

    print(f"\n  Pool Size Effect:")
    for ps in [42, 43, 44, 45]:
        cfg = f'F{ps}'
        s6 = results_p1[cfg][20000]['six']
        s5 = results_p1[cfg][20000]['five']
        print(f"    F{ps}: {s6} hits 6/6, {s5} hits 5/6, contain={contain[ps]/n_test*100:.1f}%")

    print(f"\n  SORT Ratio Effect (Pool 42):")
    sr_cfgs = [('SR50','50%'), ('SR60','60%'), ('F42','70%'), ('SR80','80%'), ('SR90','90%'), ('SR100','100%')]
    for cfg, lbl in sr_cfgs:
        if cfg in results_p1:
            s6 = results_p1[cfg][20000]['six']
            s6_10 = results_p1[cfg][10000]['six']
            print(f"    SR={lbl}: {s6} @20K, {s6_10} @10K")

    print(f"\n  Multi-Seed Effect (vs single seed):")
    comparisons = [('MS-F42', 'F42'), ('MS-F44', 'F44'), ('MS-SR80', 'SR80')]
    for ms, single in comparisons:
        if ms in results_p1 and single in results_p1:
            ms_s = results_p1[ms][20000]['six']
            sg_s = results_p1[single][20000]['six']
            delta = ms_s - sg_s
            arrow = '🔺' if delta > 0 else ('🔻' if delta < 0 else '➖')
            print(f"    {ms} vs {single}: {ms_s} vs {sg_s} @20K ({arrow} {delta:+d})")

    # Save
    output = {
        'version': 'V21 TITAN',
        'n_test': n_test,
        'timestamp': time.strftime('%Y-%m-%d %H:%M:%S'),
        'containment': {str(ps): {'count': contain[ps], 'pct': round(contain[ps]/n_test*100,2)} for ps in [42,43,44,45]},
        'phase1_configs': list(P1_CONFIGS.keys()),
        'phase2_top4': top4,
        'results': {},
        'elapsed_min': round(total_elapsed/60, 1),
        'p1_min': round(p1_elapsed/60, 1),
        'p2_min': round(p2_elapsed/60, 1),
    }
    for cfg_name in P1_CONFIGS:
        output['results'][cfg_name] = {}
        for pt in ALL_PORTS:
            r = results_all[cfg_name][pt]
            output['results'][cfg_name][str(pt)] = {
                'six': r['six'], 'five': r['five'], 'four': r['four'],
            }
    # Best per size
    for pt in ALL_PORTS:
        search_pool = top4 if pt in P2_PORTS else list(P1_CONFIGS.keys())
        ranking = [(k, results_all[k][pt]['six'], results_all[k][pt]['five']) for k in search_pool]
        ranking.sort(key=lambda x: (-x[1], -x[2]))
        output[f'best_at_{pt//1000}k'] = {'config': ranking[0][0], 'six': ranking[0][1], 'five': ranking[0][2]}

    path = os.path.join(os.path.dirname(__file__), 'models', 'v21_titan.json')
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(output, f, indent=2, ensure_ascii=False)
    print(f"\n  Saved: {path}")
    print(f"  Phase 1: {p1_elapsed/60:.1f}min | Phase 2: {p2_elapsed/60:.1f}min | Total: {total_elapsed/60:.1f}min")
    print(f"{'═'*90}")


if __name__ == '__main__':
    run()
